(function(){
const KEY='hct_his_v1';
const TABS=[['command','CC','Command center','Hospital operations overview'],['patients','PT','Patient list','Census, acuity, and chart links'],['labs','LI','Labs and imaging','Diagnostics queue and resulted work'],['pharmacy','RX','Pharmacy','Medication verification and stock'],['supplies','CS','Central supplies','Inventory and restock requests']];
const RX=[['Normal saline 1 L',42,18,'IV fluids'],['Lactated Ringers 1 L',35,14,'IV fluids'],['Ondansetron 4 mg vial',26,10,'Antiemetic'],['Oxytocin 30 units bag',18,8,'OB emergency'],['Albuterol nebules',44,20,'Respiratory'],['Regular insulin vial',16,8,'Endocrine']];
const CS=[['IV start kit',72,30,'Vascular access'],['Blood draw tube set',88,35,'Laboratory'],['Foley catheter kit',22,10,'GU'],['Sterile dressing tray',34,15,'Wound care'],['OB hemorrhage cart pack',10,6,'Emergency'],['Isolation PPE bundle',48,20,'Infection control']];
let tab='command',search='',open=false;
function E(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function msg(v){typeof toast==='function'?toast(v):console.log(v)}
function pts(){try{if(typeof state!=='undefined'&&Array.isArray(state.patients))return state.patients;const s=JSON.parse(localStorage.getItem('hct_ehr_v2')||'null');return Array.isArray(s?.patients)?s.patients:[]}catch(e){return[]}}
function init(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.inventory)return s}catch(e){}return{inventory:{pharmacy:RX.map((x,i)=>({id:'rx-'+i,name:x[0],onHand:x[1],par:x[2],category:x[3],requested:0})),supplies:CS.map((x,i)=>({id:'cs-'+i,name:x[0],onHand:x[1],par:x[2],category:x[3],requested:0}))},labStatus:{},medStatus:{},supplyRequests:[]}}
let his=init();function save(){localStorage.setItem(KEY,JSON.stringify(his))}
function ac(p){const a=String(p.acuity||'').toLowerCase();return a.includes('critical')?'red':a.includes('urgent')||a.includes('watcher')?'gold':'green'}
function ptxt(p){return`${p.lastName||''} ${p.firstName||''} ${p.mrn||''} ${p.diagnosis||''} ${p.location||''} ${p.specialty||''}`.toLowerCase()}
function fpts(){const q=search.trim().toLowerCase();return pts().filter(p=>!q||ptxt(p).includes(q))}
function diagnostics(){const rows=[];pts().forEach(p=>{(p.labs||[]).forEach((l,i)=>rows.push({id:`${p.id}-lab-${i}`,patientId:p.id,patient:`${p.lastName}, ${p.firstName}`,location:p.location||'',type:/xray|x-ray|ct|mri|ultrasound|ecg|ekg|cxr/i.test(`${l.test} ${l.note}`)?'Imaging':'Lab',name:l.test||'Diagnostic test',result:l.result||'Pending',flag:l.flag||'Pending',time:l.time||'',note:l.note||''}));(p.orders||[]).filter(o=>/lab|cbc|bmp|cmp|culture|xray|x-ray|ct|mri|ultrasound|ecg|ekg|diagnostic|imaging|lactate|fibrinogen/i.test(`${o.category} ${o.order}`)).forEach((o,i)=>rows.push({id:`${p.id}-order-${i}`,patientId:p.id,patient:`${p.lastName}, ${p.firstName}`,location:p.location||'',type:/xray|x-ray|ct|mri|ultrasound|ecg|ekg|diagnostic|imaging/i.test(`${o.category} ${o.order}`)?'Imaging':'Lab',name:o.order||'Diagnostic order',result:his.labStatus[`${p.id}-order-${i}`]||o.status||'Ordered',flag:/stat|critical/i.test(`${o.status} ${o.details}`)?'STAT':'Routine',time:'',note:o.details||''}))});return rows}
function meds(){const rows=[];pts().forEach(p=>(p.meds||[]).forEach((m,i)=>rows.push({id:`${p.id}-med-${i}`,patientId:p.id,patient:`${p.lastName}, ${p.firstName}`,location:p.location||'',med:m.name||'Medication',dose:m.dose||'',route:m.route||'',status:his.medStatus[`${p.id}-med-${i}`]||m.status||'pending',note:m.warn||m.note||''})));return rows}
function met(){const p=pts(),d=diagnostics(),m=meds();return{census:p.length,critical:p.filter(x=>ac(x)==='red').length,diagnostics:d.filter(x=>!/resulted|complete|normal|high|low|critical/i.test(x.result)).length,medPending:m.filter(x=>!/verified|dispensed|given|hold|not_given/i.test(x.status)).length,rxLow:his.inventory.pharmacy.filter(i=>i.onHand<=i.par).length,csLow:his.inventory.supplies.filter(i=>i.onHand<=i.par).length}}
function st(t,c){return`<span class="his-status ${c||''}">${E(t)}</span>`}function card(t,b,r=''){return`<section class="his-card"><div class="his-card-head"><h3>${E(t)}</h3>${r}</div><div class="his-card-body">${b}</div></section>`}function metric(l,v,d){return`<section class="his-card his-metric"><div class="his-card-body"><strong>${E(v)}</strong><span>${E(l)}</span><small>${E(d||'')}</small></div></section>`}
function command(){const m=met(),p=pts(),alerts=[...p.filter(x=>ac(x)==='red').map(x=>({title:`Critical patient: ${x.lastName}, ${x.firstName}`,body:`${x.location||'No location'} - ${x.diagnosis||'No diagnosis'}`,tab:'patients'})),...diagnostics().filter(x=>/stat|critical/i.test(`${x.flag} ${x.result}`)).slice(0,4).map(x=>({title:`Diagnostic priority: ${x.name}`,body:`${x.patient} - ${x.flag} ${x.result}`,tab:'labs'})),...his.inventory.pharmacy.filter(i=>i.onHand<=i.par).slice(0,3).map(i=>({title:`Low pharmacy stock: ${i.name}`,body:`${i.onHand} on hand, par ${i.par}`,tab:'pharmacy'})),...his.inventory.supplies.filter(i=>i.onHand<=i.par).slice(0,3).map(i=>({title:`Low supply stock: ${i.name}`,body:`${i.onHand} on hand, par ${i.par}`,tab:'supplies'}))];const a=alerts.map(x=>`<div class="his-row"><div><strong>${E(x.title)}</strong><span>${E(x.body)}</span></div><button class="btn small" data-his-tab="${x.tab}">Open</button></div>`).join('');return`<div class="his-grid">${metric('Current census',m.census,'Active EHR workspaces')}${metric('Critical acuity',m.critical,'Needs command awareness')}${metric('Diagnostics pending',m.diagnostics,'Labs and imaging queue')}${metric('Medication queue',m.medPending,'Pharmacy verification')}</div><div class="his-grid two" style="margin-top:12px;">${card('Command priorities',`<div class="his-list">${a||'<p class="his-empty">No command center alerts right now.</p>'}</div>`)}${card('Operations snapshot',`<div class="his-list"><div class="his-row"><div><strong>Pharmacy low stock</strong><span>${m.rxLow} item(s) at or below par.</span></div>${st(m.rxLow?'Action':'OK',m.rxLow?'gold':'green')}</div><div class="his-row"><div><strong>Central supply low stock</strong><span>${m.csLow} item(s) at or below par.</span></div>${st(m.csLow?'Action':'OK',m.csLow?'gold':'green')}</div><div class="his-row"><div><strong>Patient flow</strong><span>Open patient list to jump directly into the EHR chart.</span></div><button class="btn small" data-his-tab="patients">View</button></div></div>`)}</div>`}
function patients(){const rows=fpts().map(p=>`<div class="his-row"><div><strong>${E(p.lastName)}, ${E(p.firstName)}</strong><span>MRN ${E(p.mrn)} - ${E(p.location||'No location')} - ${E(p.diagnosis||'No diagnosis')}</span><small>${E(p.specialty||'General')} - ${E((p.tags||[]).join(', '))}</small></div><div class="his-actions">${st(p.acuity||'Stable',ac(p))}<button class="btn small primary" data-his-open-patient="${E(p.id)}">Open chart</button></div></div>`).join('');return card('Patient list',`<div class="his-list">${rows||'<p class="his-empty">No matching patients.</p>'}</div>`)}
function labs(){const q=search.trim().toLowerCase(),rows=diagnostics().filter(l=>!q||`${l.patient} ${l.name} ${l.type} ${l.result}`.toLowerCase().includes(q)).map(l=>{const c=/critical|stat/i.test(`${l.flag} ${l.result}`)?'red':/pending|ordered|active/i.test(l.result)?'gold':'green';return`<tr><td><strong>${E(l.patient)}</strong><br><small>${E(l.location)}</small></td><td>${E(l.type)}</td><td><strong>${E(l.name)}</strong><br><small>${E(l.note)}</small></td><td>${st(l.flag||'Routine',c)}</td><td>${E(l.result)}</td><td><button class="btn small" data-his-result="${E(l.id)}">Mark resulted</button></td></tr>`}).join('');return card('Labs and imaging queue',`<div class="table-wrap"><table class="his-table"><thead><tr><th>Patient</th><th>Type</th><th>Order</th><th>Priority</th><th>Status/result</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="6">No diagnostic work found.</td></tr>'}</tbody></table></div>`)}
function invRows(type){return his.inventory[type].filter(i=>!search||`${i.name} ${i.category}`.toLowerCase().includes(search.toLowerCase())).map(i=>{const pct=Math.min(100,Math.round(i.onHand/Math.max(i.par*2,1)*100)),low=i.onHand<=i.par;return`<tr><td><strong>${E(i.name)}</strong><br><small>${E(i.category)}</small><div class="his-bar"><span style="width:${pct}%;"></span></div></td><td>${i.onHand}</td><td>${i.par}</td><td>${st(low?'Reorder':'Stocked',low?'gold':'green')}</td><td class="his-actions"><button class="btn small" data-his-adjust="${type}:${i.id}:-1">Use</button><button class="btn small" data-his-adjust="${type}:${i.id}:5">Restock</button><button class="btn small primary" data-his-request="${type}:${i.id}">Request</button></td></tr>`}).join('')}
function pharmacy(){const q=search.toLowerCase(),queue=meds().filter(m=>!q||`${m.patient} ${m.med} ${m.status}`.toLowerCase().includes(q)).map(m=>`<div class="his-row"><div><strong>${E(m.med)} ${E(m.dose)}</strong><span>${E(m.patient)} - ${E(m.location)} - ${E(m.route)}</span><small>${E(m.note)}</small></div><div class="his-actions">${st(m.status,/pending|active/i.test(m.status)?'gold':'green')}<button class="btn small primary" data-his-verify="${E(m.id)}">Verify</button></div></div>`).join('');return`<div class="his-grid two">${card('Medication verification queue',`<div class="his-list">${queue||'<p class="his-empty">No medication queue items.</p>'}</div>`)}${card('Pharmacy inventory',`<div class="table-wrap"><table class="his-table"><thead><tr><th>Item</th><th>On hand</th><th>Par</th><th>Status</th><th></th></tr></thead><tbody>${invRows('pharmacy')}</tbody></table></div>`)}</div>`}
function supplies(){const req=his.supplyRequests.slice(-8).reverse().map(r=>`<div class="his-row"><div><strong>${E(r.item)}</strong><span>${E(r.type)} request - ${E(r.time)}</span></div>${st(r.status,'gold')}</div>`).join('');return`<div class="his-grid two">${card('Central supplies inventory',`<div class="table-wrap"><table class="his-table"><thead><tr><th>Item</th><th>On hand</th><th>Par</th><th>Status</th><th></th></tr></thead><tbody>${invRows('supplies')}</tbody></table></div>`)}${card('Restock requests',`<div class="his-list">${req||'<p class="his-empty">No restock requests yet.</p>'}</div>`)}</div>`}
function content(){return tab==='patients'?patients():tab==='labs'?labs():tab==='pharmacy'?pharmacy():tab==='supplies'?supplies():command()}
function html(){const a=TABS.find(t=>t[0]===tab)||TABS[0];return`<div class="his-shell ${open?'open':''}" id="his-shell"><div class="his-app" role="dialog" aria-label="Hospital information system"><aside class="his-side"><div class="his-brand"><strong>Hospital IS</strong><span>Command, diagnostics, pharmacy, and central supplies.</span></div><nav class="his-nav">${TABS.map(t=>`<button class="${tab===t[0]?'active':''}" data-his-tab="${t[0]}"><span class="his-ic">${t[1]}</span><span><strong>${t[2]}</strong><span>${t[3]}</span></span></button>`).join('')}</nav><button class="btn danger" id="his-close">Close HIS</button></aside><main class="his-main"><header class="his-top"><div><h2>${E(a[2])}</h2><p>${E(a[3])}</p></div><div class="his-tools"><input class="his-search" id="his-search" placeholder="Search HIS..." value="${E(search)}"><button class="btn" id="his-refresh">Refresh</button></div></header><section class="his-content">${content()}</section></main></div></div>`}
function renderHis(){let r=document.getElementById('his-root');if(!r){r=document.createElement('div');r.id='his-root';document.body.appendChild(r)}r.innerHTML=html();bind()}
function launcher(){if(document.getElementById('his-launcher'))return;const b=document.createElement('button');b.id='his-launcher';b.className='his-launcher';b.textContent='Hospital IS';document.body.appendChild(b);b.onclick=()=>{open=true;renderHis()}}
function bind(){document.getElementById('his-close')?.addEventListener('click',()=>{open=false;renderHis()});document.getElementById('his-refresh')?.addEventListener('click',renderHis);document.querySelectorAll('[data-his-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.hisTab;renderHis()});document.getElementById('his-search')?.addEventListener('input',e=>{search=e.target.value;renderHis()});document.querySelectorAll('[data-his-open-patient]').forEach(b=>b.onclick=()=>{if(typeof state!=='undefined'){state.activeId=b.dataset.hisOpenPatient;state.tab='summary';if(typeof persist==='function')persist({cloud:false});if(typeof render==='function')render()}open=false;renderHis()});document.querySelectorAll('[data-his-result]').forEach(b=>b.onclick=()=>{his.labStatus[b.dataset.hisResult]='Resulted';save();renderHis();msg('Diagnostic item marked resulted')});document.querySelectorAll('[data-his-verify]').forEach(b=>b.onclick=()=>{his.medStatus[b.dataset.hisVerify]='Verified';save();renderHis();msg('Medication verified')});document.querySelectorAll('[data-his-adjust]').forEach(b=>b.onclick=()=>{const[type,id,d]=b.dataset.hisAdjust.split(':'),item=his.inventory[type].find(x=>x.id===id);if(item)item.onHand=Math.max(0,item.onHand+Number(d));save();renderHis()});document.querySelectorAll('[data-his-request]').forEach(b=>b.onclick=()=>{const[type,id]=b.dataset.hisRequest.split(':'),item=his.inventory[type].find(x=>x.id===id);if(item){item.requested+=1;his.supplyRequests.push({type,item:item.name,time:new Date().toLocaleString(),status:'Requested'});save();renderHis();msg('Restock request created')}})}
function install(){launcher();renderHis();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open){open=false;renderHis()}})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install):install();
})();
